// 스마트워크 IA(요구사항 추가) 문서를 기준으로 정리한 퍼블 대상 화면 목록
// - 순번(no)은 원본 스프레드시트의 순번을 그대로 사용
// - 화면ID(screenId)가 있는 항목은 실제 화면 단위로, 없는 항목은 LINK/BUTTON 등 단순 요소
// - route가 지정된 항목은 이미 작업된 화면(현재 라우터 기준)으로 자동 연결됨
export interface PubListItem {
  no: number
  major: string // 1Depth 대분류
  sub?: string // 2~4Depth 소분류 경로 (있는 경우 ' > ' 로 연결)
  name: string // 화면/기능 명
  screenName?: string // 화면명(설명)
  screenId?: string // 화면ID
  type: 'PAGE' | 'POPUP' | 'BBS' | 'BUTTON' | 'LINK'
  change: '신규' | '변경' | '유지'
  note?: string
  route?: string // 이미 작업된 경우 연결할 라우트 경로
}

export const pubListItems: PubListItem[] = [
  // ── 지역경찰 > 개인수첩 > 메모 ──────────────────────────────
  { no: 4, major: '지역경찰', sub: '개인수첩 > 메모', name: '목록', screenName: '개인수첩 화면', screenId: 'PM-LPO-0101', type: 'PAGE', change: '신규' },
  { no: 5, major: '지역경찰', sub: '개인수첩 > 메모', name: '상세/수정', screenName: '상세/수정화면', screenId: 'PM-LPO-0102', type: 'PAGE', change: '신규' },
  { no: 6, major: '지역경찰', sub: '개인수첩 > 메모', name: '대기시간 초과 팝업', screenName: '대기시간 초과 팝업창', screenId: 'MO-LPO-0103', type: 'POPUP', change: '신규' },
  { no: 7, major: '지역경찰', sub: '개인수첩 > 메모', name: '등록', screenName: '등록화면', screenId: 'PM-LPO-0104', type: 'PAGE', change: '신규' },
  { no: 8, major: '지역경찰', sub: '개인수첩 > 메모', name: '음성인식 종료 팝업', screenName: '음성인식 종료 팝업창', screenId: 'MO-LPO-0105', type: 'POPUP', change: '신규' },
  // ── 지역경찰 > 개인수첩 > 알림 ──────────────────────────────
  { no: 10, major: '지역경찰', sub: '개인수첩 > 알림', name: '목록', screenName: '알림메시지 목록 화면', screenId: 'PM-LPO-0106', type: 'PAGE', change: '신규' },
  { no: 11, major: '지역경찰', sub: '개인수첩 > 알림', name: '알림상세', screenName: '알림메세지 상세 팝업', screenId: 'PM-LPO-0107', type: 'POPUP', change: '신규' },
  // ── 지역경찰 > 근무일정조회 ──────────────────────────────
  { no: 13, major: '지역경찰', sub: '근무일정조회', name: '목록', screenName: '근무일정 목록 화면', screenId: 'PM-LPO-0108', type: 'PAGE', change: '신규' },
  // ── 지역경찰 > 출동수동(원본 표기) ──────────────────────────────
  { no: 15, major: '지역경찰', sub: '출동수동', name: '목록', screenName: '출동수당 목록 화면', screenId: 'PM-LPO-0109', type: 'PAGE', change: '신규' },
  { no: 16, major: '지역경찰', sub: '출동수동', name: '출동사건정보', screenName: '출동사건정보 팝업화면', screenId: 'PM-LPO-0110', type: 'POPUP', change: '신규' },
  // ── 지역경찰 > 개인실적조회 ──────────────────────────────
  { no: 18, major: '지역경찰', sub: '개인실적조회', name: '목록', screenName: '개인실적조회 화면', screenId: 'PC-LPO-0111', type: 'PAGE', change: '신규' },
  { no: 19, major: '지역경찰', sub: '개인실적조회', name: '112신고처리', screenName: '112신고처리 실적화면', screenId: 'MO-LPO-0112', type: 'PAGE', change: '신규' },
  { no: 20, major: '지역경찰', sub: '개인실적조회', name: '즉결심판', screenName: '즉결심판 실적화면', screenId: 'MO-LPO-0113', type: 'PAGE', change: '신규' },
  { no: 21, major: '지역경찰', sub: '개인실적조회', name: '통고처분', screenName: '통고처분 실적화면', screenId: 'MO-LPO-0114', type: 'PAGE', change: '신규' },
  { no: 22, major: '지역경찰', sub: '개인실적조회', name: 'TCS단속', screenName: 'TCS단속 실적화면', screenId: 'MO-LPO-0115', type: 'PAGE', change: '신규' },
  { no: 23, major: '지역경찰', sub: '개인실적조회', name: '차량순찰', screenName: '차량순찰 실적화면', screenId: 'MO-LPO-0116', type: 'PAGE', change: '신규' },
  { no: 24, major: '지역경찰', sub: '개인실적조회', name: '도보순찰', screenName: '도보순찰 실적화면', screenId: 'MO-LPO-0117', type: 'PAGE', change: '신규' },
  { no: 25, major: '지역경찰', sub: '개인실적조회', name: '거점순찰', screenName: '거점순찰 실적화면', screenId: 'MO-LPO-0118', type: 'PAGE', change: '신규' },
  { no: 26, major: '지역경찰', sub: '개인실적조회', name: '범죄예방진단', screenName: '범죄예방진단 실적화면', screenId: 'MO-LPO-0119', type: 'PAGE', change: '신규' },
  // ── 지역경찰 > 결재함 ──────────────────────────────
  { no: 28, major: '지역경찰', sub: '결재함', name: '목록(결재요청자)', screenName: '결제함(결재요청자) 목록화면', screenId: 'PM-LPO-0120', type: 'PAGE', change: '신규' },
  { no: 29, major: '지역경찰', sub: '결재함', name: '목록(결재승인자)', screenName: '결제함(결재승인자) 목록화면', screenId: 'PM-LPO-0121', type: 'PAGE', change: '신규' },
  { no: 30, major: '지역경찰', sub: '화면설정', name: '화면설정', screenName: '메인화면 설정 화면', screenId: 'PM-LPO-0122', type: 'PAGE', change: '신규' },
  { no: 32, major: '지역경찰', sub: '블루투스', name: '목록', screenName: '블루투스 연결 목록 및 프린터 테스트 인쇄 화면', screenId: 'MO-LPO-0123', type: 'PAGE', change: '변경' },
  // ── 지역경찰 > 근무일지(甲) ──────────────────────────────
  { no: 35, major: '지역경찰', sub: '근무일지 > 근무일지(甲)', name: '근무지정표작성', screenName: '근무지정표작성 화면', screenId: 'PC-LPO-0201', type: 'PAGE', change: '변경' },
  { no: 36, major: '지역경찰', sub: '근무일지 > 근무일지(甲)', name: '근무지정표', screenName: '근무지정표 화면', screenId: 'PC-LPO-0202', type: 'PAGE', change: '변경' },
  { no: 37, major: '지역경찰', sub: '근무일지 > 근무일지(甲)', name: '근무자', screenName: '근무자 화면', screenId: 'PC-LPO-0203', type: 'PAGE', change: '변경' },
  { no: 38, major: '지역경찰', sub: '근무일지 > 근무일지(甲)', name: '근무자 추가관리', screenName: '근무자 추가관리 팝업', screenId: 'PC-LPO-0204', type: 'POPUP', change: '변경', route: '/view/lpo/PC-LPO-0204.vue' },
  { no: 39, major: '지역경찰', sub: '근무일지 > 근무일지(甲)', name: '자원근무자 관리', screenName: '자원근무자 팝업창', screenId: 'PC-LPO-0205', type: 'PAGE', change: '변경' },
  { no: 40, major: '지역경찰', sub: '근무일지 > 근무일지(甲)', name: '사고자 관리', screenName: '사고자 팝업창', screenId: 'PC-LPO-0206', type: 'POPUP', change: '변경' },
  { no: 41, major: '지역경찰', sub: '근무일지 > 근무일지(甲)', name: '근무관리', screenName: '근무관리 팝업창', screenId: 'PC-LPO-0207', type: 'PAGE', change: '변경' },
  { no: 42, major: '지역경찰', sub: '근무일지 > 근무일지(甲)', name: '시간관리', screenName: '시간관리 팝업창', screenId: 'PC-LPO-0208', type: 'POPUP', change: '변경' },
  { no: 43, major: '지역경찰', sub: '근무일지 > 근무일지(甲)', name: '순찰구역', screenName: '순찰구역 관리 화면', screenId: 'PC-LPO-0209', type: 'POPUP', change: '변경' },
  { no: 44, major: '지역경찰', sub: '근무일지 > 근무일지(甲)', name: '순찰구역 상세', screenName: '순찰구역 상세 팝업창', screenId: 'PC-LPO-0210', type: 'POPUP', change: '변경' },
  { no: 45, major: '지역경찰', sub: '근무일지 > 근무일지(甲)', name: '甲지 일괄출력', screenName: '갑지 일괄출력 팝업창', screenId: 'PC-LPO-0211', type: 'POPUP', change: '변경' },
  { no: 46, major: '지역경찰', sub: '근무일지 > 근무일지(甲)', name: '근무 사용자 선택', screenName: '근무 사용자 선택 팝업창', screenId: 'PC-LPO-0212', type: 'POPUP', change: '변경' },
  { no: 47, major: '지역경찰', sub: '근무일지 > 근무일지(甲)', name: '중점사항 입력', screenName: '중점사항 입력 팝업창', screenId: 'PC-LPO-0213', type: 'POPUP', change: '변경' },
  { no: 48, major: '지역경찰', sub: '근무일지 > 근무일지(甲)', name: '근무지정표 복사', screenName: '근무지정표 복사 팝업창', screenId: 'PC-LPO-0224', type: 'PAGE', change: '변경' },
  { no: 50, major: '지역경찰', sub: '근무일지(甲) > 기본주기설정', name: '목록', screenName: '기본주기 목록화면', screenId: 'PC-LPO-0214', type: 'PAGE', change: '변경' },
  { no: 52, major: '지역경찰', sub: '근무일지(甲) > 사고자/자원근무자 현황', name: '사고자 현황', screenName: '사고자 현황 화면', screenId: 'PC-LPO-0215', type: 'PAGE', change: '변경' },
  { no: 53, major: '지역경찰', sub: '근무일지(甲) > 사고자/자원근무자 현황', name: '자원근무자 현황', screenName: '자원근무자 현황 화면', screenId: 'PC-LPO-0216', type: 'PAGE', change: '변경' },
  // ── 지역경찰 > 근무일지(乙) ──────────────────────────────
  { no: 56, major: '지역경찰', sub: '근무일지 > 근무일지(乙) > 근무일지(乙) 등록', name: '목록', screenName: '근무일지(乙) 등록 리스트 화면', screenId: 'PM-LPO-0217', type: 'PAGE', change: '변경' },
  { no: 57, major: '지역경찰', sub: '근무일지 > 근무일지(乙) > 근무일지(乙) 등록', name: '등록', screenName: '근무일지(乙) 등록 화면', screenId: 'MO-LPO-0218', type: 'PAGE', change: '변경' },
  { no: 58, major: '지역경찰', sub: '근무일지 > 근무일지(乙) > 근무일지(乙) 등록', name: '112누락정보', screenName: '112누락정보 팝업창', screenId: 'PM-LPO-0219', type: 'POPUP', change: '변경' },
  { no: 59, major: '지역경찰', sub: '근무일지 > 근무일지(乙) > 근무일지(乙) 등록', name: '112신고', screenName: '112신고 내역 상세 팝업창', screenId: 'PM-LPO-0220', type: 'POPUP', change: '변경' },
  { no: 60, major: '지역경찰', sub: '근무일지 > 근무일지(乙) > 근무일지(乙) 등록', name: '처리자 관리', screenName: '처리자 관리 팝업창', screenId: 'PM-LPO-0221', type: 'POPUP', change: '변경' },
  { no: 61, major: '지역경찰', sub: '근무일지 > 근무일지(乙) > 근무일지(乙) 등록', name: '파일업로드', screenName: '파일 업로드 팝업창', screenId: 'PM-LPO-0222', type: 'POPUP', change: '변경' },
  { no: 63, major: '지역경찰', sub: '근무일지 > 근무일지(乙) > 근무일지(乙) 조회', name: '목록', screenName: '근무일지(乙) 조회 화면', screenId: 'PM-LPO-0223', type: 'PAGE', change: '변경' },
  // ── 지역경찰 > 인수인계 ──────────────────────────────
  { no: 66, major: '지역경찰', sub: '인수인계 > 인수인계 작성', name: '상세내역', screenName: '인수인계 화면', screenId: 'PC-LPO-0301', type: 'PAGE', change: '변경' },
  { no: 67, major: '지역경찰', sub: '인수인계 > 인수인계 작성', name: '인쇄', type: 'BUTTON', change: '변경', note: '레포팅툴 연동' },
  { no: 68, major: '지역경찰', sub: '인수인계 > 인수인계 작성', name: '저장', type: 'BUTTON', change: '변경' },
  { no: 69, major: '지역경찰', sub: '인수인계 > 인수인계 작성', name: '인계저장(인계자)', type: 'BUTTON', change: '변경' },
  { no: 70, major: '지역경찰', sub: '인수인계 > 인수인계 작성', name: '인수관 확인(인수자)', type: 'BUTTON', change: '변경' },
  { no: 71, major: '지역경찰', sub: '인수인계 > 인수인계 작성', name: '확인관 확인(확인자)', type: 'BUTTON', change: '변경' },
  { no: 72, major: '지역경찰', sub: '인수인계 > 인수인계 작성', name: '점검관 확인(점검자)', type: 'BUTTON', change: '변경' },
  { no: 73, major: '지역경찰', sub: '인수인계 > 인수인계 작성', name: '인수인계 취소', screenName: '인수인계 취소 팝업창', screenId: 'PC-LPO-0302', type: 'POPUP', change: '변경' },
  { no: 75, major: '지역경찰', sub: '인수인계 > 월별 인수인계 현황', name: '목록', screenName: '월별 인수인계 현황 화면', screenId: 'PC-LPO-0304', type: 'PAGE', change: '변경' },
  // ── 지역경찰 > 현장업무 ──────────────────────────────
  { no: 77, major: '지역경찰', sub: '현장업무', name: '현장서류 목록', screenName: '현장서류 목록 화면', screenId: 'MO-LPO-0401', type: 'PAGE', change: '변경' },
  { no: 78, major: '지역경찰', sub: '현장업무', name: '지명통보 사실 통지서', screenName: '지명통보 사실 통지서 화면', screenId: 'MO-LPO-0402', type: 'PAGE', change: '변경' },
  { no: 79, major: '지역경찰', sub: '현장업무', name: '실종/가출 소재발견 기초질문지', screenName: '실종/가출 소재발견 기초질문지 화면', screenId: 'MO-LPO-0403', type: 'PAGE', change: '변경' },
  { no: 80, major: '지역경찰', sub: '현장업무', name: '스토킹/교제폭력 경고장', screenName: '스토킹/교제폭력 경고장 화면', screenId: 'MO-LPO-0404', type: 'PAGE', change: '변경' },
  { no: 81, major: '지역경찰', sub: '현장업무', name: '스토킹/교제폭력 피해자 안내서', screenName: '스토킹/교제폭력 피해자 안내서 화면', screenId: 'MO-LPO-0405', type: 'PAGE', change: '변경' },
  { no: 82, major: '지역경찰', sub: '현장업무', name: '긴급응급조치 통지서', screenName: '긴급응급조치 통지서 화면', screenId: 'MO-LPO-0406', type: 'PAGE', change: '변경' },
  { no: 83, major: '지역경찰', sub: '현장업무', name: '정신질환자 응급입원 판단 매뉴얼', screenName: '정신질환자 응급입원 판단 매뉴얼 화면', screenId: 'MO-LPO-0407', type: 'PAGE', change: '변경' },
  { no: 84, major: '지역경찰', sub: '현장업무', name: '피구호자 인계서', screenName: '피구호자 인계서 화면', screenId: 'MO-LPO-0408', type: 'PAGE', change: '변경' },
  { no: 85, major: '지역경찰', sub: '현장업무', name: '통합판단조사표', screenName: '통합판단조사표 바로가기', type: 'LINK', change: '변경' },
  { no: 86, major: '지역경찰', sub: '현장업무', name: '아동폭력', screenName: '아동폭력 바로가기', type: 'LINK', change: '변경' },
  { no: 87, major: '지역경찰', sub: '현장업무', name: '성폭력 피해자 안내서', screenName: '성폭력 피해자 안내서 화면', screenId: 'MO-LPO-0410', type: 'PAGE', change: '변경' },
  { no: 88, major: '지역경찰', sub: '현장업무', name: '범죄피해자 안내서', screenName: '범죄피해자 안내서 화면', screenId: 'MO-LPO-0411', type: 'PAGE', change: '변경' },
  { no: 90, major: '지역경찰', sub: '현장업무 > 참고 체크리스트', name: '목록', screenName: '참고 체크리스트 화면', screenId: 'MO-LPO-0412', type: 'PAGE', change: '변경' },
  { no: 91, major: '지역경찰', sub: '현장업무 > 참고 체크리스트', name: '사실혼판단체크리스트', screenName: '사실혼판단체크리스트 화면', screenId: 'MO-LPO-0413', type: 'PAGE', change: '변경' },
  { no: 92, major: '지역경찰', sub: '현장업무 > 참고 체크리스트', name: '가정폭력 경고장', screenName: '가정폭력 경고장 화면', screenId: 'MO-LPO-0414', type: 'PAGE', change: '변경' },
  { no: 93, major: '지역경찰', sub: '현장업무 > 참고 체크리스트', name: '전화금융사기체크리스트', screenName: '전화금융사기체크리스트 화면', screenId: 'MO-LPO-0415', type: 'PAGE', change: '변경' },
  { no: 94, major: '지역경찰', sub: '현장업무 > 참고 체크리스트', name: '디지털성범죄 피해자 인도 체크리스트', screenName: '디지털성범죄 피해자 인도 체크리스트 화면', screenId: 'MO-LPO-0416', type: 'PAGE', change: '변경' },
  { no: 95, major: '지역경찰', sub: '현장업무 > 참고 체크리스트', name: '자살시도자 현장 대화법', screenName: '자살시도자 현장 대화법 화면', screenId: 'MO-LPO-0417', type: 'PAGE', change: '변경' },
  { no: 96, major: '지역경찰', sub: '현장업무 > 참고 체크리스트', name: '현장경찰을 위한 신종 범죄 대응 설명자료', screenName: '현장경찰을 위한 신종 범죄 대응 설명자료 화면', screenId: 'MO-LPO-0418', type: 'PAGE', change: '변경' },
  { no: 97, major: '지역경찰', sub: '현장업무 > 참고 체크리스트', name: '정신질환 보호관찰 종료자', screenName: '정신질환 보호관찰 종료자 화면', screenId: 'MO-LPO-0419', type: 'PAGE', change: '변경' },
  { no: 98, major: '지역경찰', sub: '현장업무 > 참고 체크리스트', name: '지문 신원확인', screenName: '지문 신원확인 화면', screenId: 'MO-LPO-0420', type: 'PAGE', change: '변경' },
  // ── 지역경찰 > 출동수당 ──────────────────────────────
  { no: 101, major: '지역경찰', sub: '출동수당 > 출동수당 조회', name: '목록', screenName: '출동수당 조회 화면', screenId: 'PM-LPO-0501', type: 'PAGE', change: '변경' },
  { no: 102, major: '지역경찰', sub: '출동수당 > 출동수당 조회', name: '상세내역', screenName: '출동수당 상세내역 화면', screenId: 'PM-LPO-0502', type: 'PAGE', change: '변경' },
  { no: 104, major: '지역경찰', sub: '출동수당 > 승인관리', name: '목록', screenName: '승인관리 화면', screenId: 'PM-LPO-0503', type: 'PAGE', change: '변경' },
  // ── 지역경찰 > 관내현황 ──────────────────────────────
  { no: 106, major: '지역경찰', sub: '관내현황', name: '상세내역', screenName: '관내현황 상세내역', screenId: 'PC-LPO-0601', type: 'PAGE', change: '변경' },
  { no: 107, major: '지역경찰', sub: '관내현황', name: '순찰차별 순찰구역', screenName: '순찰차별 상세구역 팝업창', screenId: 'PC-LPO-0602', type: 'POPUP', change: '변경' },
  { no: 108, major: '지역경찰', sub: '관내현황', name: '행정동검색', screenName: '행정동 검색 팝업창', screenId: 'PC-LPO-0603', type: 'POPUP', change: '변경' },
  { no: 109, major: '지역경찰', sub: '관내현황', name: '순찰구역 상세', screenName: '순찰구역 상세 팝업창', screenId: 'PC-LPO-0604', type: 'POPUP', change: '변경' },
  // ── 지역경찰 > 장비관리 ──────────────────────────────
  { no: 112, major: '지역경찰', sub: '장비관리 > 기동장비 탭', name: '목록', screenName: '기동장비 목록', screenId: 'PC-LPO-0701', type: 'PAGE', change: '변경' },
  { no: 113, major: '지역경찰', sub: '장비관리 > 기동장비 탭', name: '등록/상세/수정', screenName: '기동장비 등록/상세/수정 팝업창', screenId: 'PC-LPO-0702', type: 'POPUP', change: '변경' },
  { no: 114, major: '지역경찰', sub: '장비관리 > 기동장비 탭', name: '112차량 조회', screenName: '112차량 조회 팝업창', screenId: 'PC-LPO-0703', type: 'POPUP', change: '변경' },
  { no: 116, major: '지역경찰', sub: '장비관리 > 통신장비 탭', name: '목록', screenName: '통신장비 목록', screenId: 'PC-LPO-0704', type: 'PAGE', change: '변경' },
  { no: 117, major: '지역경찰', sub: '장비관리 > 통신장비 탭', name: '등록/상세/수정', screenName: '통신장비 등록/상세/수정 팝업창', screenId: 'PC-LPO-0705', type: 'POPUP', change: '변경' },
  { no: 119, major: '지역경찰', sub: '장비관리 > 무기 탭', name: '목록', screenName: '무기목록', screenId: 'PC-LPO-0706', type: 'PAGE', change: '변경' },
  { no: 120, major: '지역경찰', sub: '장비관리 > 무기 탭', name: '등록/상세/수정', screenName: '무기 등록/상세/수정 팝업창', screenId: 'PC-LPO-0707', type: 'POPUP', change: '변경' },
  { no: 122, major: '지역경찰', sub: '장비관리 > 탄약 탭', name: '목록', screenName: '탄약 목록', screenId: 'PC-LPO-0708', type: 'PAGE', change: '변경' },
  { no: 123, major: '지역경찰', sub: '장비관리 > 탄약 탭', name: '등록/상세/수정', screenName: '탄약 등록/상세/수정 팝업창', screenId: 'PC-LPO-0709', type: 'POPUP', change: '변경' },
  { no: 125, major: '지역경찰', sub: '장비관리 > 수갑 탭', name: '목록', screenName: '수갑 목록', screenId: 'PC-LPO-0710', type: 'PAGE', change: '변경' },
  { no: 126, major: '지역경찰', sub: '장비관리 > 수갑 탭', name: '등록/상세/수정', screenName: '수갑 등록/상세/수정 팝업창', screenId: 'PC-LPO-0711', type: 'POPUP', change: '변경' },
  { no: 128, major: '지역경찰', sub: '장비관리 > 기타 탭', name: '목록', screenName: '기타 목록', screenId: 'PC-LPO-0712', type: 'PAGE', change: '변경' },
  { no: 129, major: '지역경찰', sub: '장비관리 > 기타 탭', name: '등록/상세/수정', screenName: '기타 등록/상세/수정 팝업창', screenId: 'PC-LPO-0713', type: 'POPUP', change: '변경' },
  { no: 130, major: '지역경찰', sub: '장비관리 > 기타 탭', name: '장비 유지보수 이력', screenName: '장비 유지보수 이력 팝업창', screenId: 'PC-LPO-0714', type: 'POPUP', change: '변경' },
  // ── 지역경찰 > 인사관리/기초정보 ──────────────────────────────
  { no: 132, major: '지역경찰', sub: '인사관리', name: '상세내역', screenName: '인사관리 화면', screenId: 'PC-LPO-0801', type: 'PAGE', change: '변경' },
  { no: 133, major: '지역경찰', sub: '인사관리', name: '부서 찾기전/출입', screenName: '부서찾기 팝업창', screenId: 'PC-LPO-0802', type: 'PAGE', change: '변경' },
  { no: 134, major: '지역경찰', sub: '지역경찰 기초정보 관리', name: '지역경찰 기초정보 관리', screenName: '지역경찰 통계관리 화면', type: 'LINK', change: '변경', note: 'WISE OLAP 연동' },
  { no: 135, major: '지역경찰', sub: '지역경찰 기초정보 관리', name: '목록', screenName: '기초통계 목록', screenId: 'PC-LPO-0901', type: 'PAGE', change: '신규' },
  { no: 136, major: '지역경찰', sub: '지역경찰 기초정보 관리', name: '상세', screenName: '기초통계 상세', screenId: 'PC-LPO-0902', type: 'PAGE', change: '신규' },
  { no: 137, major: '지역경찰', sub: '지역경찰 기초정보 관리', name: '등록', screenName: '기초통계 엑셀 업로드', screenId: 'PC-LPO-0903', type: 'PAGE', change: '신규' },

  // ── 생활안전 > 범죄예방진단 ──────────────────────────────
  { no: 140, major: '생활안전', sub: '범죄예방진단', name: '간이 범죄예방진단 목록', screenId: 'PM-PUB-0101', type: 'PAGE', change: '변경' },
  { no: 141, major: '생활안전', sub: '범죄예방진단', name: '상세', screenName: '간이 범죄예방진단 상세', screenId: 'PM-PUB-0102', type: 'POPUP', change: '변경' },
  { no: 142, major: '생활안전', sub: '범죄예방진단', name: 'CPO 입력·관리 목록', screenName: 'CPO 입력관리 목록', screenId: 'PM-PUB-0103', type: 'PAGE', change: '변경' },
  { no: 143, major: '생활안전', sub: '범죄예방진단', name: '범죄예방진단결과(보관용)', screenId: 'PM-PUB-0104', type: 'POPUP', change: '변경' },
  { no: 144, major: '생활안전', sub: '범죄예방진단', name: '범죄예방진단결과(CPO확인용)', screenId: 'PM-PUB-0105', type: 'POPUP', change: '변경' },
  { no: 145, major: '생활안전', sub: '범죄예방진단', name: '진단추가', screenId: 'PM-PUB-0106', type: 'POPUP', change: '변경' },
  { no: 146, major: '생활안전', sub: '범죄예방진단', name: '신규(등록)', screenName: '진단신규(등록)', screenId: 'PM-PUB-0107', type: 'POPUP', change: '변경' },
  { no: 147, major: '생활안전', sub: '범죄예방진단', name: '상세', screenName: '범죄예방진단 상세', screenId: 'PM-PUB-0108', type: 'POPUP', change: '변경' },
  { no: 148, major: '생활안전', sub: '범죄예방진단', name: '사진자료', screenId: 'PM-PUB-0109', type: 'POPUP', change: '변경' },
  { no: 149, major: '생활안전', sub: '범죄예방진단', name: '간이진단통보자료', screenId: 'PM-PUB-0110', type: 'POPUP', change: '변경' },
  { no: 150, major: '생활안전', sub: '범죄예방진단', name: '이력보기', screenId: 'PM-PUB-0111', type: 'POPUP', change: '변경' },
  { no: 151, major: '생활안전', sub: '범죄예방진단', name: '참고사항 상세', screenId: 'PM-PUB-0112', type: 'PAGE', change: '변경' },
  { no: 152, major: '생활안전', sub: '범죄예방진단', name: '업로드', screenName: '참고사항 업로드', screenId: 'PM-PUB-0113', type: 'POPUP', change: '변경' },
  { no: 153, major: '생활안전', sub: '범죄예방진단', name: '우수시설인증 리스트', screenName: '진단인증 리스트', screenId: 'PM-PUB-0114', type: 'PAGE', change: '변경' },
  { no: 154, major: '생활안전', sub: '범죄예방진단', name: '체크리스트', screenName: '진단인증 체크리스트', screenId: 'PM-PUB-0115', type: 'PAGE', change: '변경' },
  { no: 155, major: '생활안전', sub: '범죄예방진단', name: 'Pre-CAS', type: 'LINK', change: '유지' },
  // ── 생활안전 > 여성청소년 ──────────────────────────────
  { no: 157, major: '생활안전', sub: '여성청소년', name: '통합판단조사표 목록', screenId: 'PM-PUB-0201', type: 'PAGE', change: '변경' },
  { no: 158, major: '생활안전', sub: '여성청소년', name: '미도착/미종결 목록', screenName: '112신고조회 미도착/미종결 목록', screenId: 'PM-PUB-0202', type: 'POPUP', change: '변경' },
  { no: 159, major: '생활안전', sub: '여성청소년', name: '통합판단조사표 수정', screenName: '미도착/미종결 목록 통합판단조사표 수정', screenId: 'PM-PUB-0203', type: 'PAGE', change: '변경' },
  { no: 160, major: '생활안전', sub: '여성청소년', name: '통합판단조사표 등록', screenName: '수정 통합판단조사표 등록', screenId: 'PM-PUB-0204', type: 'PAGE', change: '변경' },
  { no: 161, major: '생활안전', sub: '여성청소년', name: '아동학대 목록 등록', screenName: '아동학대 목록', screenId: 'PM-PUB-0205', type: 'PAGE', change: '변경' },
  { no: 162, major: '생활안전', sub: '여성청소년', name: '아동학대 수정', screenId: 'PM-PUB-0206', type: 'PAGE', change: '변경' },
  { no: 163, major: '생활안전', sub: '여성청소년', name: '아동학대 등록', screenId: 'PM-PUB-0207', type: 'PAGE', change: '변경' },
  { no: 164, major: '생활안전', sub: '여성청소년', name: '맞춤형 순찰 현황', type: 'LINK', change: '유지' },
  { no: 165, major: '생활안전', sub: '여성청소년 > (구)자료조회', name: '가정폭력 목록/상세', screenId: 'PC-PUB-0208', type: 'PAGE', change: '변경' },
  { no: 166, major: '생활안전', sub: '여성청소년 > (구)자료조회', name: '아동학대 목록/상세', screenId: 'PC-PUB-0209', type: 'PAGE', change: '변경' },
  { no: 167, major: '생활안전', sub: '여성청소년 > (구)자료조회', name: '스토킹 목록/상세', screenId: 'PC-PUB-0210', type: 'PAGE', change: '변경' },
  // ── 생활안전 > 방범협력단체 ──────────────────────────────
  { no: 170, major: '생활안전', sub: '방범협력단체 > 단체정보리스트', name: '목록', screenName: '단체정보 목록', screenId: 'PC-PUB-0301', type: 'PAGE', change: '변경' },
  { no: 171, major: '생활안전', sub: '방범협력단체 > 단체정보리스트', name: '상세/수정', screenName: '단체정보 상세/수정', screenId: 'PC-PUB-0302', type: 'PAGE', change: '변경' },
  { no: 172, major: '생활안전', sub: '방범협력단체 > 단체정보리스트', name: '등록', screenName: '단체정보 등록', screenId: 'PM-PUB-0303', type: 'PAGE', change: '변경' },
  { no: 174, major: '생활안전', sub: '방범협력단체 > 단체활동기록', name: '목록/상세/수정/등록', screenId: 'PM-PUB-0304', type: 'PAGE', change: '변경' },
  { no: 176, major: '생활안전', sub: '방범협력단체 > 단체활동현황', name: '단체현황', screenName: '단체현황화면', screenId: 'PC-PUB-0305', type: 'PAGE', change: '변경' },
  { no: 177, major: '생활안전', sub: '방범협력단체 > 단체활동현황', name: '활동현황', screenName: '활동현황 화면', screenId: 'PC-PUB-0306', type: 'PAGE', change: '변경' },
  // ── 생활안전 > 해바라기센터 ──────────────────────────────
  { no: 180, major: '생활안전', sub: '해바라기센터 관리', name: '목록', screenName: '해바라기센터 목록', screenId: 'PM-PUB-0401', type: 'PAGE', change: '변경' },
  { no: 181, major: '생활안전', sub: '해바라기센터 관리', name: '상세', screenName: '해바라기센터 상세', screenId: 'PM-PUB-0402', type: 'POPUP', change: '변경' },
  { no: 182, major: '생활안전', sub: '해바라기센터 관리', name: '등록', screenName: '해바라기센터 등록', screenId: 'PM-PUB-0403', type: 'POPUP', change: '변경' },
  { no: 183, major: '생활안전', sub: '해바라기센터 관리', name: '센터 사용자', screenName: '해바라기센터 사용자', screenId: 'PM-PUB-0404', type: 'PAGE', change: '변경' },
  { no: 185, major: '생활안전', sub: '해바라기센터 > 조사예약', name: '목록(월별)', screenName: '조사예약 목록(월별)', screenId: 'PM-PUB-0405', type: 'PAGE', change: '변경' },
  { no: 186, major: '생활안전', sub: '해바라기센터 > 조사예약', name: '목록(주간별)', screenName: '조사예약 목록(주간별)', screenId: 'PM-PUB-0406', type: 'PAGE', change: '변경' },
  { no: 187, major: '생활안전', sub: '해바라기센터 > 조사예약', name: '상세', screenName: '조사예약 상세', screenId: 'PM-PUB-0407', type: 'POPUP', change: '변경' },
  { no: 188, major: '생활안전', sub: '해바라기센터 > 조사예약', name: '등록', screenName: '조사예약 등록', screenId: 'PM-PUB-0408', type: 'POPUP', change: '변경' },
  // ── 생활안전 > 보호조치 대응팀 ──────────────────────────────
  { no: 191, major: '생활안전', sub: '보호조치 대응팀 > 주취자 센터 병상 현황', name: '주취자센터병상현황 목록/상세', screenId: 'PM-PUB-0409', type: 'PAGE', change: '변경' },
  { no: 192, major: '생활안전', sub: '보호조치 대응팀 > 주취자 센터 병상 현황', name: '주취자센터병상현황 상세', screenName: '주취자센터병상현황 상세(모바일)', screenId: 'MO-PUB-0410', type: 'POPUP', change: '신규' },
  { no: 193, major: '생활안전', sub: '보호조치 대응팀 > 주취자 센터 병상 현황', name: '주취자등록&병상배정 등록', screenId: 'PM-PUB-0411', type: 'PAGE', change: '신규' },
  { no: 194, major: '생활안전', sub: '보호조치 대응팀 > 주취자 센터 병상 현황', name: '주취자센터 등록', screenId: 'PM-PUB-0412', type: 'POPUP', change: '신규' },
  { no: 195, major: '생활안전', sub: '보호조치 대응팀 > 주취자 센터관리', name: '주취자센터 목록', screenId: 'PM-PUB-0413', type: 'PAGE', change: '신규' },
  { no: 196, major: '생활안전', sub: '보호조치 대응팀 > 주취자 센터관리', name: '주취자센터 등록', screenId: 'PM-PUB-0414', type: 'PAGE', change: '신규' },
  { no: 197, major: '생활안전', sub: '보호조치 대응팀 > 주취자 센터관리', name: '주취자입퇴소현황', screenId: 'PM-PUB-0415', type: 'PAGE', change: '신규' },
  { no: 199, major: '생활안전', sub: '보호조치 대응팀 > 정신 응급 대응팀', name: '목록', screenName: '정신응급대응팀 목록', screenId: 'PM-PUB-0416', type: 'PAGE', change: '신규' },
  { no: 200, major: '생활안전', sub: '보호조치 대응팀 > 정신 응급 대응팀', name: '등록', screenName: '정신응급대응팀 등록', screenId: 'PM-PUB-0417', type: 'PAGE', change: '신규' },
  // ── 생활안전 > 폴케어 ──────────────────────────────
  { no: 202, major: '생활안전', sub: '폴케어', name: '목록', screenName: '폴케어 목록화면', screenId: 'MO-PUB-0501', type: 'PAGE', change: '변경' },
  { no: 203, major: '생활안전', sub: '폴케어', name: '지원제도 안내', type: 'LINK', change: '변경' },
  { no: 204, major: '생활안전', sub: '폴케어', name: '형사절차와 나의 권리', type: 'LINK', change: '변경' },
  { no: 206, major: '생활안전', sub: '폴케어 > 조회', name: '목록', screenName: '조회 목록 화면', screenId: 'MO-PUB-0601', type: 'PAGE', change: '변경' },
  { no: 207, major: '생활안전', sub: '폴케어 > 조회', name: '사회적약자보호 종합플랫폼', type: 'LINK', change: '변경' },
  { no: 208, major: '생활안전', sub: '폴케어 > 조회', name: '폴리폰', type: 'LINK', change: '변경' },
  { no: 209, major: '생활안전', sub: '폴케어 > 조회', name: '미성년자 조회', screenId: 'MO-PUB-0602', type: 'PAGE', change: '변경' },
  { no: 210, major: '생활안전', sub: '폴케어 > 조회', name: '생년월일 선택', screenName: '생년월일 선택 팝업창', screenId: 'MO-PUB-0601', type: 'POPUP', change: '변경', note: '원본 자료에 화면ID가 중복 표기됨' },
  { no: 211, major: '생활안전', sub: '폴케어 > 조회', name: '미성년자 조회 결과', screenName: '미성년자 조회 결과 화면', screenId: 'MO-PUB-0601', type: 'PAGE', change: '변경', note: '원본 자료에 화면ID가 중복 표기됨' },
  // ── 생활안전 > 보고서 ──────────────────────────────
  { no: 213, major: '생활안전', sub: '보고서', name: '물리력 보고서', type: 'PAGE', change: '변경' },
  { no: 214, major: '생활안전', sub: '보고서', name: '목록', screenName: '물리력 보고서 화면', screenId: 'PM-PUB-0701', type: 'PAGE', change: '변경' },
  { no: 216, major: '생활안전', sub: '보고서 > 기타 영상기기 사용 보고서', name: '목록', screenName: '기타 영상기기 사용 보고서 화면', screenId: 'PM-PUB-0702', type: 'PAGE', change: '변경' },

  // ── 탄력순찰 ──────────────────────────────
  { no: 219, major: '탄력순찰', sub: '요청관리', name: '목록', screenName: '요청관리', screenId: 'PM-FLP-0101', type: 'PAGE', change: '변경' },
  { no: 220, major: '탄력순찰', sub: '범죄 안전 지도', name: '탄력순찰상세', screenId: 'PM-FLP-0201', type: 'POPUP', change: '변경' },
  { no: 221, major: '탄력순찰', sub: '범죄 안전 지도', name: '종결처리', screenId: 'PM-FLP-0214', type: 'POPUP', change: '신규' },
  { no: 222, major: '탄력순찰', sub: '범죄 안전 지도', name: '신고현황', screenName: '신고현황 검색', screenId: 'PM-FLP-0202', type: 'POPUP', change: '변경' },
  { no: 223, major: '탄력순찰', sub: '범죄 안전 지도', name: '신고다발지', screenName: '신고다발지 검색', screenId: 'PM-FLP-0203', type: 'POPUP', change: '변경' },
  { no: 224, major: '탄력순찰', sub: '범죄 안전 지도', name: '사건종별 설정', screenId: 'PM-FLP-0204', type: 'POPUP', change: '변경' },
  { no: 225, major: '탄력순찰', sub: '범죄 안전 지도', name: '탄력순찰등록', screenId: 'PM-FLP-0205', type: 'POPUP', change: '변경' },
  { no: 226, major: '탄력순찰', sub: '범죄 안전 지도', name: '요청목록', screenId: 'PM-FLP-0206', type: 'POPUP', change: '변경' },
  { no: 227, major: '탄력순찰', sub: '범죄 안전 지도', name: '성범죄', screenName: '성범죄 검색', screenId: 'PM-FLP-0207', type: 'POPUP', change: '변경' },
  { no: 228, major: '탄력순찰', sub: '범죄 안전 지도', name: '상세정보', screenId: 'PM-FLP-0208', type: 'POPUP', change: '변경' },
  { no: 229, major: '탄력순찰', sub: '범죄 안전 지도', name: '전자발찌', screenName: '전자발찌 검색', screenId: 'PM-FLP-0209', type: 'POPUP', change: '변경' },
  { no: 230, major: '탄력순찰', sub: '범죄 안전 지도', name: '정신질환', screenName: '정신질환 검색', screenId: 'PM-FLP-0210', type: 'POPUP', change: '변경' },
  { no: 231, major: '탄력순찰', sub: '범죄 안전 지도', name: '순찰노선', screenName: '순찰노선 검색', screenId: 'PM-FLP-0211', type: 'POPUP', change: '변경' },
  { no: 232, major: '탄력순찰', sub: '범죄 안전 지도', name: '화면분할', screenId: 'PM-FLP-0212', type: 'POPUP', change: '변경' },
  { no: 233, major: '탄력순찰', sub: '범죄 안전 지도', name: '우범지역', screenId: 'PM-FLP-0213', type: 'POPUP', change: '변경' },
  { no: 234, major: '탄력순찰', sub: '범죄 안전 지도', name: '관서경계', screenId: 'PM-FLP-0215', type: 'POPUP', change: '변경' },
  { no: 235, major: '탄력순찰', sub: '범죄 안전 지도', name: 'POI조회', screenId: 'PM-FLP-0216', type: 'POPUP', change: '변경' },
  { no: 236, major: '탄력순찰', sub: '탄력순찰 이행현황', name: '탄력순찰 이행현황', screenId: 'PM-FLP-0301', type: 'PAGE', change: '신규' },
  { no: 237, major: '탄력순찰', sub: '탄력순찰 이행실적', name: '탄력순찰 이행실적', screenId: 'PM-FLP-0401', type: 'PAGE', change: '변경' },

  // ── 사건대응 시나리오 ──────────────────────────────
  { no: 239, major: '사건대응 시나리오', name: '검색', screenName: '사건대응 시나리오 검색화면', screenId: 'PM-IRC-0101', type: 'PAGE', change: '신규', note: 'LLM, STT 연동' },
  { no: 240, major: '사건대응 시나리오', name: '음성인식 진행중', screenName: '음성인식 진행중 팝업(통합검색 공통)', screenId: 'PM-IRC-0102', type: 'POPUP', change: '신규' },
  { no: 241, major: '사건대응 시나리오', name: '음성인식 결과', screenName: '음성인식 결과 팝업(통합검색 공통)', screenId: 'PM-IRC-0103', type: 'POPUP', change: '신규' },
  { no: 242, major: '사건대응 시나리오', name: '검색결과', screenName: '사건대응 시나리오 결과화면', screenId: 'PM-IRC-0104', type: 'PAGE', change: '신규', note: 'LLM, STT 연동' },

  // ── 통계 ──────────────────────────────
  { no: 244, major: '통계', name: '112통계 바로가기', type: 'LINK', change: '유지' },
  { no: 245, major: '통계', name: '지역경찰 근무통계', screenName: '지역경찰 통계화면', type: 'LINK', change: '변경', note: 'WISE OLAP 연동' },

  // ── 게시판 ──────────────────────────────
  { no: 248, major: '게시판', sub: '공지사항', name: '리스트', screenName: '공지사항 리스트 화면', screenId: 'PM-COM-1001', type: 'BBS', change: '변경' },
  { no: 249, major: '게시판', sub: '공지사항', name: '상세내역', screenName: '공지사항 상세내역 화면', screenId: 'PM-COM-1002', type: 'BBS', change: '변경' },
  { no: 250, major: '게시판', sub: '공지사항', name: '수정', screenName: '공지사항 수정 화면', screenId: 'PM-COM-1003', type: 'BBS', change: '변경' },
  { no: 251, major: '게시판', sub: '공지사항', name: '등록', screenName: '공지사항 등록 화면', screenId: 'PM-COM-1004', type: 'BBS', change: '변경' },
  { no: 253, major: '게시판', sub: 'Q&A', name: '리스트', screenName: '장애처리 리스트 화면', screenId: 'PM-COM-1101', type: 'BBS', change: '변경' },
  { no: 254, major: '게시판', sub: 'Q&A', name: '상세내역', screenName: '장애처리 상세내역 화면', screenId: 'PM-COM-1102', type: 'BBS', change: '변경' },
  { no: 255, major: '게시판', sub: 'Q&A', name: '수정', screenId: 'PM-COM-1103', type: 'BBS', change: '변경' },
  { no: 256, major: '게시판', sub: 'Q&A', name: '등록', screenId: 'PM-COM-1104', type: 'BBS', change: '변경' },
  { no: 258, major: '게시판', sub: '지역경찰 시책 우수사례', name: '리스트', screenId: 'PM-COM-1201', type: 'BBS', change: '변경' },
  { no: 259, major: '게시판', sub: '지역경찰 시책 우수사례', name: '상세내역', screenId: 'PM-COM-1202', type: 'BBS', change: '변경' },
  { no: 260, major: '게시판', sub: '지역경찰 시책 우수사례', name: '수정', screenId: 'PM-COM-1203', type: 'BBS', change: '변경' },
  { no: 261, major: '게시판', sub: '지역경찰 시책 우수사례', name: '등록', screenId: 'PM-COM-1204', type: 'BBS', change: '변경' },
  { no: 263, major: '게시판', sub: '현장조치 우수사례', name: '리스트', screenId: 'PM-COM-1301', type: 'BBS', change: '변경' },
  { no: 264, major: '게시판', sub: '현장조치 우수사례', name: '상세내역', screenId: 'PM-COM-1302', type: 'BBS', change: '변경' },
  { no: 265, major: '게시판', sub: '현장조치 우수사례', name: '수정', screenId: 'PM-COM-1303', type: 'BBS', change: '변경' },
  { no: 266, major: '게시판', sub: '현장조치 우수사례', name: '등록', screenId: 'PM-COM-1304', type: 'BBS', change: '변경' },
  { no: 269, major: '게시판', sub: '교육자료 나눔터 > 교육훈련 우수사례', name: '리스트', screenId: 'PM-COM-1401', type: 'BBS', change: '변경' },
  { no: 270, major: '게시판', sub: '교육자료 나눔터 > 교육훈련 우수사례', name: '상세내역', screenId: 'PM-COM-1402', type: 'BBS', change: '변경' },
  { no: 271, major: '게시판', sub: '교육자료 나눔터 > 교육훈련 우수사례', name: '수정', screenId: 'PM-COM-1403', type: 'BBS', change: '변경' },
  { no: 272, major: '게시판', sub: '교육자료 나눔터 > 교육훈련 우수사례', name: '등록', screenId: 'PM-COM-1404', type: 'BBS', change: '변경' },
  { no: 274, major: '게시판', sub: '교육자료 나눔터 > 상시학습자료', name: '리스트', screenId: 'PM-COM-1501', type: 'BBS', change: '변경' },
  { no: 275, major: '게시판', sub: '교육자료 나눔터 > 상시학습자료', name: '상세내역', screenId: 'PM-COM-1502', type: 'BBS', change: '변경' },
  { no: 276, major: '게시판', sub: '교육자료 나눔터 > 상시학습자료', name: '수정', screenId: 'PM-COM-1503', type: 'BBS', change: '변경' },
  { no: 277, major: '게시판', sub: '교육자료 나눔터 > 상시학습자료', name: '등록', screenId: 'PM-COM-1504', type: 'BBS', change: '변경' },
  { no: 279, major: '게시판', sub: '교육자료 나눔터 > 법령·지침·매뉴얼', name: '리스트', screenId: 'PM-COM-1601', type: 'BBS', change: '변경' },
  { no: 280, major: '게시판', sub: '교육자료 나눔터 > 법령·지침·매뉴얼', name: '상세내역', screenId: 'PM-COM-1602', type: 'BBS', change: '변경' },
  { no: 281, major: '게시판', sub: '교육자료 나눔터 > 법령·지침·매뉴얼', name: '수정', screenId: 'PM-COM-1603', type: 'BBS', change: '변경' },
  { no: 282, major: '게시판', sub: '교육자료 나눔터 > 법령·지침·매뉴얼', name: '등록', screenId: 'PM-COM-1604', type: 'BBS', change: '변경' },
  { no: 284, major: '게시판', sub: '교육자료 나눔터 > 현장대응팁', name: '리스트', screenId: 'PM-COM-1701', type: 'BBS', change: '변경' },
  { no: 285, major: '게시판', sub: '교육자료 나눔터 > 현장대응팁', name: '상세내역', screenId: 'PM-COM-1702', type: 'BBS', change: '변경' },
  { no: 286, major: '게시판', sub: '교육자료 나눔터 > 현장대응팁', name: '수정', screenId: 'PM-COM-1703', type: 'BBS', change: '변경' },
  { no: 287, major: '게시판', sub: '교육자료 나눔터 > 현장대응팁', name: '등록', screenId: 'PM-COM-1704', type: 'BBS', change: '변경' },
  { no: 290, major: '게시판', sub: '자료실 > 범죄예방진단', name: '리스트', screenName: '범죄예방진단 리스트 화면', screenId: 'PM-COM-1901', type: 'BBS', change: '변경' },
  { no: 291, major: '게시판', sub: '자료실 > 범죄예방진단', name: '상세내역', screenId: 'PM-COM-1902', type: 'BBS', change: '변경' },
  { no: 292, major: '게시판', sub: '자료실 > 범죄예방진단', name: '수정', screenId: 'PM-COM-1903', type: 'BBS', change: '변경' },
  { no: 293, major: '게시판', sub: '자료실 > 범죄예방진단', name: '등록', screenId: 'PM-COM-1904', type: 'BBS', change: '변경' },
  { no: 296, major: '게시판', sub: '현장공감 TalkTalk > 경찰청 주요 정책', name: '리스트', screenId: 'PM-COM-2001', type: 'BBS', change: '변경' },
  { no: 297, major: '게시판', sub: '현장공감 TalkTalk > 경찰청 주요 정책', name: '상세내역', screenId: 'PM-COM-2002', type: 'BBS', change: '변경' },
  { no: 298, major: '게시판', sub: '현장공감 TalkTalk > 경찰청 주요 정책', name: '수정', screenId: 'PM-COM-2003', type: 'BBS', change: '변경' },
  { no: 299, major: '게시판', sub: '현장공감 TalkTalk > 경찰청 주요 정책', name: '등록', screenId: 'PM-COM-2004', type: 'BBS', change: '변경' },
  { no: 301, major: '게시판', sub: '현장공감 TalkTalk > 정책 제안 및 건의사항', name: '리스트', screenId: 'PM-COM-2101', type: 'BBS', change: '변경' },
  { no: 302, major: '게시판', sub: '현장공감 TalkTalk > 정책 제안 및 건의사항', name: '상세내역', screenId: 'PM-COM-2102', type: 'BBS', change: '변경' },
  { no: 303, major: '게시판', sub: '현장공감 TalkTalk > 정책 제안 및 건의사항', name: '수정', screenId: 'PM-COM-2103', type: 'BBS', change: '변경' },
  { no: 304, major: '게시판', sub: '현장공감 TalkTalk > 정책 제안 및 건의사항', name: '등록', screenId: 'PM-COM-2104', type: 'BBS', change: '변경' },

  // ── 시스템 관리 ──────────────────────────────
  { no: 308, major: '시스템 관리', sub: '시스템 운영관리 > 사용자 권한관리', name: '상세내역', screenName: '사용자 권한관리 상세화면', screenId: 'PC-COM-2201', type: 'PAGE', change: '변경', route: '/component/PC-COM-2201' },
  { no: 309, major: '시스템 관리', sub: '시스템 운영관리 > 사용자 권한관리', name: '사용자정보 팝업창', screenName: '사용자 정보 상세 팝업창', screenId: 'PC-COM-2202', type: 'POPUP', change: '신규' },
  { no: 311, major: '시스템 관리', sub: '시스템 운영관리 > 메뉴관리', name: '상세내역', screenName: '메뉴관리 화면', screenId: 'PC-COM-2203', type: 'PAGE', change: '변경' },
  { no: 313, major: '시스템 관리', sub: '시스템 운영관리 > 권한관리', name: '상세내역', screenName: '권한관리 화면', screenId: 'PC-COM-2204', type: 'PAGE', change: '변경' },
  { no: 314, major: '시스템 관리', sub: '시스템 운영관리 > 권한관리', name: '부서 조회', screenName: '부서조회 팝업창', screenId: 'PC-COM-2205', type: 'POPUP', change: '신규' },
  { no: 316, major: '시스템 관리', sub: '시스템 운영관리 > 코드관리', name: '상세내역', screenName: '코드관리 화면', screenId: 'PC-COM-2206', type: 'PAGE', change: '변경' },
  { no: 318, major: '시스템 관리', sub: '시스템 모니터링', name: '메뉴사용통계', screenName: '메뉴접속통계 화면', screenId: 'PC-COM-2301', type: 'PAGE', change: '변경' },
  { no: 319, major: '시스템 관리', sub: '시스템 모니터링', name: '접속이력', screenName: '접속 이력 화면', screenId: 'PC-COM-2302', type: 'PAGE', change: '변경' },
  { no: 320, major: '시스템 관리', sub: '시스템 모니터링', name: '변경이력조회', screenName: '시스템 모니터링 화면', screenId: 'PC-COM-2303', type: 'PAGE', change: '신규' },
  { no: 323, major: '시스템 관리', sub: '홈페이지 관리 > 게시판관리', name: '목록', screenName: '게시판관리 화면', screenId: 'PC-COM-2401', type: 'PAGE', change: '변경' },
  { no: 324, major: '시스템 관리', sub: '홈페이지 관리 > 게시판관리', name: '상세내역', screenName: '게시판관리 상세화면', screenId: 'PC-COM-2402', type: 'PAGE', change: '변경' },
  { no: 325, major: '시스템 관리', sub: '홈페이지 관리 > 게시판관리', name: '등록', screenName: '게시판관리 등록화면', screenId: 'PC-COM-2403', type: 'PAGE', change: '변경' },
  { no: 327, major: '시스템 관리', sub: '홈페이지 관리 > 팝업 관리', name: '목록', screenName: '팝업관리 화면', screenId: 'PC-COM-2404', type: 'PAGE', change: '변경' },
  { no: 328, major: '시스템 관리', sub: '홈페이지 관리 > 팝업 관리', name: '상세내역', screenName: '팝업관리 상세화면', screenId: 'PC-COM-2405', type: 'PAGE', change: '변경' },
  { no: 329, major: '시스템 관리', sub: '홈페이지 관리 > 팝업 관리', name: '등록', screenName: '팝업관리 등록화면', screenId: 'PC-COM-2406', type: 'PAGE', change: '변경' },
  { no: 330, major: '시스템 관리', sub: '앱관리', name: '앱관리', screenName: '앱 버전 등 앱 관리 화면', screenId: 'PC-COM-2501', type: 'PAGE', change: '신규' },
  { no: 332, major: '시스템 관리', sub: '도움말 관리기능', name: '목록', screenName: '도움말 목록 화면', screenId: 'PC-COM-2601', type: 'PAGE', change: '신규' },
  { no: 333, major: '시스템 관리', sub: '도움말 관리기능', name: '등록', screenName: '도움말 등록 화면', screenId: 'PC-COM-2602', type: 'PAGE', change: '신규' },

  // ── 공통 ──────────────────────────────
  { no: 335, major: '공통', name: '로그인', screenName: '로그인 화면', screenId: 'PM-COM-0101', type: 'PAGE', change: '변경' },
  { no: 336, major: '공통', name: '공인인증서 등록 팝업', screenId: 'PM-COM-0102', type: 'POPUP', change: '변경' },
  { no: 337, major: '공통', name: '메인', screenName: '메인화면', screenId: 'PM-COM-0201', type: 'PAGE', change: '변경' },
  { no: 338, major: '공통', name: '에러페이지', screenName: '에러페이지 화면', screenId: 'PM-COM-0301', type: 'PAGE', change: '변경' },
  { no: 340, major: '공통', sub: '주소검색', name: '도로명 찾기', screenName: '도로명 찾기 탭', screenId: 'PC-COM-0401', type: 'PAGE', change: '변경' },
  { no: 341, major: '공통', sub: '주소검색', name: '법정동 찾기', screenName: '법정동 찾기 탭', screenId: 'PC-COM-0402', type: 'PAGE', change: '변경' },
  { no: 342, major: '공통', sub: '주소검색', name: 'GIS 찾기', screenName: 'GIS 찾기 탭', screenId: 'PC-COM-0403', type: 'PAGE', change: '변경' },
  { no: 343, major: '공통', name: '112신고조회', screenName: '112 신고조회 팝업창', screenId: 'PM-COM-0501', type: 'POPUP', change: '변경' },
  { no: 344, major: '공통', name: '부서검색', screenName: '부서검색 팝업창', screenId: 'PC-COM-0601', type: 'POPUP', change: '변경' },
  { no: 345, major: '공통', name: '사용자찾기', screenName: '사용자 찾기 팝업창', screenId: 'PC-COM-0701', type: 'POPUP', change: '변경' },
  { no: 347, major: '공통', sub: '통합검색', name: '검색창', screenName: '통합검색창 화면', screenId: 'PM-COM-0801', type: 'PAGE', change: '신규' },
  { no: 348, major: '공통', sub: '통합검색', name: '검색결과', screenName: '통합검색 결과 화면', screenId: 'PM-COM-0802', type: 'PAGE', change: '신규' },
  { no: 349, major: '공통', name: '사이트맵', screenName: '사이트맵 화면', screenId: 'PM-COM-0901', type: 'PAGE', change: '변경' },
  { no: 350, major: '공통', name: '로그아웃', type: 'BUTTON', change: '변경' },
]

export const pubListMajors = Array.from(new Set(pubListItems.map((item) => item.major)))
